- name: Import mysql-client
  import_tasks: mysql-client.yml

- name: copy backup script
  template: 
    src: "{{ item }}.j2" 
    dest: /home/{{ username }}/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0770
  loop:
    - backup-ca.sh
    - backup-db.sh
    - backup-web.sh

- name: Ensures backup directories exists
  file: 
    path: /home/{{ username }}/{{ item }}
    state: directory 
    owner: "{{ username }}" 
    group: "{{ username }}" 
    mode: 0750
  loop: "{{ groups['backupclients'] }}"

- name: schedule backups
  cron:
   name: start backup script
   job: /home/{{ username }}/{{ item }}
   minute: "0"
   hour: "0"
   user: "{{ username }}"
  loop:
    - backup-ca.sh
    - backup-db.sh
    - backup-web.sh