- name: Install required packages
  apt: 
    name: "{{item}}"
    state: present
  with_items:
    - python3-pip

- name: Install pip packages
  pip:
    name: "{{item}}"
  with_items:
    - wheel
    - gunicorn
    - flask
