- hosts: backupservers, backupclients
  become: yes
  tasks:
    - name: install rsync
      package:
        name: rsync
        state: present

- name: setup backup servers
  hosts: backupservers
  become: yes
  roles:
    - backup