---
- hosts: clientservers
  become: yes
  roles:
    - xfce-desktop

- hosts: clientservers
  become: yes
  tasks:
    - name: Create client user
      user:
        name: alice
        state: present
        shell: /bin/bash
        password: "{{ client_password | password_hash('sha512') }}"
  
    - name: Install firefox
      apt:
        name: firefox-esr
        state: present

    - name: Add domain name to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: ".*[ \t]{{ item }}$"
        line: "{{ web_ip_address }} {{ item }}"
        state: present
      with_items:
        - imovies.ch
        - www.imovies.ch