---
- hosts: clientservers
  become: true
  tasks:
    - name: Create client user
      user:
        name: alice
        state: present
        shell: /bin/bash
        password: "{{ client_password | password_hash('sha512') }}"

- hosts: clientservers
  become: yes
  roles:
    - xfce-desktop

- hosts: clientservers
  become: yes
  tasks:
    - name: Install firefox
      apt:
        name: firefox-esr
        state: present