---
- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: "yes"
        update_cache: yes

- hosts: dbservers, webservers, caservers
  become: yes
  tasks:
    - name: Install Python pip
      apt: 
        name: python3-pip 
        update_cache: true 
        state: present 
        force_apt_get: yes

- hosts: dbservers, webservers
  become: yes
  tasks:
    - name: Install Python packages
      pip: 
        name: mysql-connector-python
        
- hosts: webservers, caservers
  become: yes
  tasks:
    - name: Add users
      user:
        name: "{{ username }}"
        password_lock: yes
        shell: "{{ usershell }}"

- hosts: all
  become: yes
  tasks:
    - name: Create tls folder
      file:
        path: /etc/asl/certs
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy root certificate
      copy:
        src: /vagrant/ca/certs/root_cert.pem
        dest: /etc/asl/certs/root_cert.pem
        owner: root
        group: root
        mode: 0644

- hosts: webservers, caservers, dbservers
  become: yes
  tasks:
    - name: Copy key and certificate
      copy:
        src: /vagrant/ca/ica/{{ item }}s/{{ ansible_host }}_{{ item }}.pem
        dest: /etc/asl/certs/{{ ansible_host }}_{{ item }}.pem
        owner: root
        group: root
        mode: 0644
      with_items:
        - key
        - cert
      