- hosts: webservers, caservers, dbservers, backupservers
  become: yes
  tasks:
    - name: Add users
      user:
        name: "{{ username }}"
        password_lock: yes
        shell: "{{ usershell }}"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519

    - name: Copy public key
      copy:
        src: /home/{{ username }}/.ssh/id_ed25519.pub
        dest: /vagrant/shared/ssh_keys/{{ inventory_hostname }}_id_ed25519.pub
        remote_src: yes

- hosts: backupservers
  become: yes
  tasks:
    - name: Install public key on backup host
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/vagrant/shared/ssh_keys/' + item + '_id_ed25519.pub') }}"
      with_items: 
        - "{{ groups['backupclients'] }}"
    
    - name: Add backupclients to known_hosts
      known_hosts:
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan ' + hostvars[item].ansible_host) }}"
        path: /home/{{ username}}/.ssh/known_hosts
      with_items: 
        - "{{ groups['backupclients'] }}"


- hosts: backupclients
  become: yes
  tasks:
    - name: Install public key on backup clients
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/vagrant/shared/ssh_keys/backup_id_ed25519.pub') }}"

    - name: Add backup server to known_hosts
      known_hosts:
        name: "{{ hostvars['backup'].ansible_host }}"
        key: "{{ lookup('pipe', 'ssh-keyscan ' + hostvars['backup'].ansible_host) }}"
        path: /home/{{ username}}/.ssh/known_hosts
