---
- hosts: clientservers
  become: yes
  tasks:
    - name: Create admin user
      user:
        name: admin
        state: present
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{ admin_password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519
      
    - name: Copy public key to vagrant share
      copy:
        src: /home/admin/.ssh/id_ed25519.pub
        dest: /vagrant/shared/ssh_keys/client_id_ed25519.pub
        remote_src: yes

- hosts: configservers
  become: yes
  tasks:
    - name: Create admin user
      user:
        name: admin
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
        password_lock: yes
      
    - name: Allow admin user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^admin"
        line: "admin ALL=(ALL) NOPASSWD: ALL"
    
    - name: Add authorized keys
      authorized_key:
        user: admin
        state: present
        key: "{{ lookup('file', '/vagrant/shared/ssh_keys/client_id_ed25519.pub') }}"
