- hosts: webservers, caservers, dbservers, backupservers
  become: yes
  tasks:
    - name: Add users
      user:
        name: "{{ username }}"
        password_lock: yes
        shell: "{{ usershell }}"
