---
- hosts: all
  become: yes
  tasks:
    - name: Create tls folder
      file:
        path: /etc/asl/certs
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy root certificate
      copy:
        src: /vagrant/ca/certs/root_cert.pem
        dest: /etc/asl/certs/root_cert.pem
        owner: root
        group: root
        mode: 0644

- hosts: webservers, caservers, dbservers
  become: yes
  tasks:
    - name: Copy key and certificate
      copy:
        src: /vagrant/ca/ica/{{ item }}s/{{ ansible_host }}_{{ item }}.pem
        dest: /etc/asl/certs/{{ ansible_host }}_{{ item }}.pem
        owner: root
        group: root
        mode: 0644
      with_items:
        - key
        - cert

- hosts: webservers
  become: yes
  tasks:
    - name: Restart webserver service
      systemd:
        name: webserver
        enabled: yes
        state: started

    - name: Restart nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
  tags: [ 'never', 'certificate']

- hosts: caservers
  become: yes
  tasks:
    - name: Restart caserver service
      systemd:
        name: caserver
        enabled: yes
        state: started

    - name: Restart nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
  tags: [ 'never', 'certificate']

- hosts: dbservers
  become: yes
  tasks:
    - name: Restart mariadb service
      systemd:
        name: mariadb
        enabled: yes
        state: started
  tags: [ 'never', 'certificate']
