- name: Install xfce4 desktop
  apt:
    name: "{{ xfce_packages }}"
    state: present
    update_cache: true
  notify: Restart login manager service

- name: Copy admin cert
  copy:
    src: /vagrant/ca/eca/keys/6_key.pem
    dest: /home/admin/Desktop
    owner: admin
    mode: 0664