---
- name: Install nginx
  apt:
    name: nginx
    update_cache: yes

- name: Apply nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ site_name }}
  notify: Restart nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/{{ site_name }}
    dest: /etc/nginx/sites-enabled/{{ site_name }}
    state: link
  notify: Restart nginx