- name: Download Mysql
  apt:
    deb: https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb
    state: present
- name: Installing Mysql and dependencies
  package:
   name: "{{item}}"
   state: present
   update_cache: yes
  loop:
   - mysql-client
   - python3-mysqldb
   - libmysqlclient-dev
  become: yes


- name: copy db connect script
  copy: src=../files/imovies-connect.py dest=/var/tmp/imovies-connect.py owner=root group=root mode=0770