- name: Add user "web-server"
  user:
    name: web-server

- name: copy web-server
  copy: 
    src: ../../../../../web-server/
    dest: /home/web-server/web-server 
    owner: web-server 
    group: web-server
    mode: u=rwx

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /home/web-server/web-server/requirements.txt

- name: install setfacl
  apt:
    name: acl
    state: present

- name: create log file
  file:
    path: /home/web-server/web-server/web-server.log
    owner: web-server
    group: web-server
    attributes: +a
    mode: u=rw

# - name: Copy certificates for tls public connections
# - name: Copy certificates for ca, db for server authentication
# - name: Copy certificates, key for internal tls connections, client authentication

- name: move service into /etc
  command: mv /home/web-server/web-server/web-server.service /etc/systemd/system

- name: start web server service
  command: sudo systemctl start web-server
  become: yes
  become_user: web-server


